#! /bin/bash

echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

if pgrep -l dnsmasq > /dev/null
then
	pkill dnsmasq
fi

dnsmasq -d --dhcp-range=10.133.105.10,10.133.105.33
